# gobo build
name: Build

on:
  pull_request:
    branches: ['main', 'master']
  push:
    branches: ['main', 'master']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Set up goboscript
      shell: bash
      run: |
        export PATH="$PATH:~/.local/bin"
        export PATH="$PATH:~/.cargo/bin"
        
        cargo install --git https://github.com/aspizu/goboscript

      # above code is from:
      # run: curl -fsSL https://raw.githubusercontent.com/aspizu/goboscript/refs/heads/main/install.sh | sh
      # but backpack and sb2gs have been removed
    - name: Install dependencies for testing
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U inflator

    - name: Set inflator token
      shell: bash
      run: |
        inflate set auth-token ${{ secrets.GH_VIEW_TOKEN }}
        
    - name: Build demo
      shell: bash
      run: |        
        cd demo
        inflate install -r inflator.toml  # inflate demo dependencies, e.g. assert
        inflate
        goboscript build

    - name: Build test
      shell: bash
      run: |        
        cd test
        inflate install -r inflator.toml  # inflate test dependencies, e.g. assert
        inflate
        goboscript build

    - name: Commit demo.sb3
      uses: EndBug/add-and-commit@v9
      with:
        add: "demo/demo.sb3 --force"
        message: 'build: demo.sb3'
        default_author: github_actions

    - name: Commit test.sb3
      uses: EndBug/add-and-commit@v9
      with:
        add: "test/test.sb3 --force"
        message: 'build: test.sb3'
        default_author: github_actions
