name: Tests

on:
  pull_request:
    branches: ['main', 'master']
  push:
    branches: ['main', 'master']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:      
    - uses: actions/checkout@v4
    - uses: inflated-goboscript/gstest@v0.1.5
      with:
        token: ${{ secrets.GH_VIEW_TOKEN }}
        suffix: "-i arg"
